[build]
builder = "NIXPACKS"

[deploy]
startCommand = "bash start.sh"
restartPolicyMaxRetries = 10
restartPolicyWindowMs = 60000
numReplicas = 1

[env]
TELEGRAM_API_ID = "36263007"
TELEGRAM_API_HASH = "9c9769a227e52ef9a197c43cd67f167f"
SESSION_STRING = "1AZWarzMBu15noJ--xOAuqqCcOSfYepW3U3nagr8HDIMGMk9fn0GypmP-YNyVgO88BZZZUQG0FQsIpxKeySkp9BQtLXaK0rqd5xj8QevvTPeO8JVAELxMPyULhYV0pBfVW6wzbSH58Gk8u7ZFYlAz-kY5q8sH4nXjfdBT68eL8U9wrVhIbpHu1Kb7h42cju1O9xVkaA8d6VKha3KnOknuYZ7UV_aRJGOeMz5sIMosuECBMBSp74YWDDeeQa4Ri1W73LPJPbT6etQLI-DsJ3H3Z5SrWryjhPyNTLzRGGBnuSmSH8jY5PXqR58jIs14j_26q697LtWOvBG_vo6mWCJnTbMTo3xxMsM="
TARGET_GROUP_ID = "-1003957567812"
RECIPIENT_CHAT_ID = "7772844148"
PORT = "8080"
RAILPACK_PYTHON_VERSION = "3.11"
